"""Contains a test that is commented out but fails when executed"""

import unittest


# class TestFail(unittest.TestCase):
#     def testFailBoolean(self):
#         """A simple test that fails as long as the universe is still operating normally"""
#         self.assertTrue(False)

#     def testFailEquality(self):
#         """A more complex test that fails when maths is still maths"""
#         expected_num = 1
#         actual_num = 2

#         self.assertEqual(expected_num, actual_num)

#     def testFailList(self):
#         """A test that fails because two lists are not equal"""
#         a = [1, 2, 3]
#         b = [1, 2, 4]

#         self.assertListEqual(a, b)

#     def testFailDict(self):
#         """A test that fails because two dictionaries are not equal"""
#         expected_dict = {"a": 1, "b": 2}
#         actual_dict = {"a": 1, "b": 3}

#         self.assertDictEqual(expected_dict, actual_dict)
